BEAM_DIAMETER = 44;
BEAM_LOOP_DELTA = 1;
BEAM_LOOP_DIAMETER = BEAM_DIAMETER + 2 * BEAM_LOOP_DELTA;
DWARF_ANGLE = 85;
LIVING_ROOM_ANGLE = 37;

LOOP_WALL_HEIGHT = 15;
LOOP_ATTACHMENT_WIDTH = (sin(45) *  BEAM_LOOP_DIAMETER);
LOOP_ATTACHMENT_HEIGHT = (LOOP_ATTACHMENT_WIDTH/2) / tan(DWARF_ANGLE/2);

SCREW_BLOCK_WIDTH = 15;
BRACKET_WALL = 3;
BRACKET_LENGTH = 5;
JOINT_SAFETY = 0.2;

ELECTRONIC_BASE_HEIGHT = 2;
ELECTRONIC_DIAMETER = 44; // must be large enough to fit the electronics

$fn = 200;
